version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      weekly-batch:
        patterns:
          - "*"
    target-branch: "develop"
