from collections.abc import Iterator
from typing import Any

class ConnectionError(Exception): ...
class BufferTooShort(ConnectionError): ...
class TimeoutError(ConnectionError): ...

class Connection:
    max_fwu_block_size: int | None

    def __init__(self, device: str, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def recv(self, maxlength: int | None = ...) -> bytes: ...
    def send(self, buf: bytes, offset: int = ..., size: int | None = ...) -> None: ...

def open(device: str, **kwargs: Any) -> Connection: ...
def scan() -> Iterator[tuple[str, str]]: ...
