from typing import Any, NamedTuple

from . import connection as connection

class ControlUnit:
    class Status(NamedTuple):
        fuel: tuple[int, ...]
        start: int
        mode: int
        pit: tuple[bool, ...]
        display: int

        FUEL_MODE: int
        REAL_MODE: int
        PIT_LANE_MODE: int
        LAP_COUNTER_MODE: int

    class Timer(NamedTuple):
        address: int
        timestamp: int
        sector: int

    PACE_CAR_ESC_BUTTON_ID: int
    START_ENTER_BUTTON_ID: int
    SPEED_BUTTON_ID: int
    BRAKE_BUTTON_ID: int
    FUEL_BUTTON_ID: int
    CODE_BUTTON_ID: int

    def __init__(self, device: str | connection.Connection, **kwargs: Any) -> None: ...
    def close(self) -> None: ...
    def clrpos(self) -> None: ...
    def ignore(self, mask: int) -> None: ...
    def poll(self) -> Status | Timer | None: ...
    def press(self, button_id: int) -> bytes: ...
    def request(self, buf: bytes, maxlength: int | None = ...) -> bytes: ...
    def reset(self) -> None: ...
    def setbrake(self, address: int, value: int) -> None: ...
    def setfuel(self, address: int, value: int) -> None: ...
    def setlap(self, value: int) -> None: ...
    def setlap_hi(self, value: int) -> None: ...
    def setlap_lo(self, value: int) -> None: ...
    def setpos(self, address: int, position: int) -> None: ...
    def setspeed(self, address: int, value: int) -> None: ...
    def setword(
        self, word: int, address: int, value: int, repeat: int = ...
    ) -> bytes: ...
    def start(self) -> None: ...
    def version(self) -> str | None: ...
    def fwu_start(self) -> None: ...
    def fwu_write(self, data: bytes) -> None: ...
