from typing import Any

class ProtocolError(Exception): ...
class ChecksumError(Exception): ...

def chksum(buf: bytes, offset: int = ..., size: int | None = ...) -> int: ...
def pack(fmt: str, *args: Any) -> bytes: ...
def unpack(fmt: str, buf: bytes) -> tuple[Any, ...]: ...
